---
### Provision of a DOCKER Container (where everything will be created, testing...)
- name: Bring up a Docker for Artifactory
  hosts: localhost
  gather_facts: false
  vars:
    inventory:
      - name: ualter_artifactory
        image: "chrismeyers/centos6"
        ports:
          - "18081:8081"
          - "13306:3306"
        expose:
          - "18081:8081"
          - "13306:3306"
  roles:
    - role: provision_docker
      provision_docker_inventory: "{{inventory}}"

### Install MYSQL
- name: Install MySQL
  hosts: docker_containers  
  vars:
  - mysql_user_home: /root
    mysql_user_name: root
    mysql_user_password: root
    mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
    mysql_users:
    - name: example_user
      host: "%"
      password: strongpass
      priv: "example_db.*:ALL"
  roles:
    - role: geerlingguy.mysql
      become: yes

### Install Java
- name: Install Java
  hosts: docker_containers
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
      become: yes

### Install Artifactory      
- name: Install Artifactory
  hosts: docker_containers
  vars:
   - artifactory_database: mysql
     mysql_root_password: root
  roles:
    - role: ujr-artifactory

