---
### Provision of a DOCKER Container (where everything will be created, testing...)
- name: Bring up a Docker for Artifactory
  hosts: localhost
  gather_facts: false
  vars:
    inventory:
      - name: ualter_artifactory
        image: "chrismeyers/centos6"
        ports:
          - "18081:8081"
          - "13306:3306"
        expose:
          - "18081:8081"
          - "13306:3306"
      - name: ualter_
        image: "chrismeyers/centos6"
  roles:
    - role: provision_docker
      provision_docker_inventory: "{{inventory}}"
  tasks:
    - name: Group primary
      add_host:
        hostname: "{{item}}"
        groups: primary
      with_items:
        - ualter_artifactory
      tags: provision_docker
    - name: Group secondary
      add_host:
        hostname: "{{item}}"
        groups: secondary
      with_items:
        - ualter_
      tags: provision_docker      

### Install MYSQL
- name: Install MySQL
  hosts: primary  
  vars:
  - mysql_user_home: /root
    mysql_user_name: root
    mysql_user_password: root
    mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
    mysql_users:
    - name: example_user
      host: "%"
      password: strongpass
      priv: "example_db.*:ALL"
  roles:
    - role: geerlingguy.mysql
      become: yes

### Install Java
- name: Install Java
  hosts: primary:secondary
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
      become: yes

### Install Artifactory      
- name: Install Artifactory
  hosts: primary
  vars:
   - artifactory_database: mysql
     mysql_root_password: root
  roles:
    - role: ujr-artifactory    

