---
### DOCKER (Where everything will be created, testing...)
- name: Bring up a Docker for Artifactory
  hosts: localhost
  gather_facts: false
  vars:
    inventory:
      - name: ualter_artifactory
        image: "chrismeyers/centos6"
  roles:
    - role: provision_docker
      provision_docker_inventory: "{{inventory}}"

### MYSQL
- name: Install MySQL Dependency
  hosts: docker_containers  
  vars:
  - mysql_user_home: /root
    mysql_user_name: root
    mysql_user_password: root
    mysql_databases:
    - name: example_db
      encoding: latin1
      collation: latin1_general_ci
    mysql_users:
    - name: example_user
      host: "%"
      password: strongpass
      priv: "example_db.*:ALL"
  roles:
    - role: geerlingguy.mysql
      become: yes

#- name: Bring up Artifactory
#  vars:
#  - artifactory_database: mysql
#  
#  roles:
#     - { role: bbaassssiiee.artifactory }