---
# hosts could have been "remote" or "all" as well
- hosts: local
#  connection: local
  become: yes
  become_user: root
  tasks:
   - name: Install Nginx
     apt:
       name: nginx
       state: latest
       update_cache: true
   - name: Start Nginx
     service:
         name: nginx
         state: started
     notify:
      - Check Nginx    

  handlers:
     - name: Check Nginx
       service:
         name: nginx
         state: started       