---
- name: Bring up docker containers for Ujr
  hosts: localhost
  gather_facts: false
  vars:
    inventory:
      - name: docker_ualter
        image: "chrismeyers/centos7"
  roles:
    - role: chrismeyersfsu.provision_docker
      provision_docker_inventory: "{{inventory}}"

- name: Just a playground playbook
  hosts: docker_containers
  vars:
    folder_name: UALTER_JR
    any_text_value: UALTER_JUNIOR
  roles:
    - { role: ujr-artifactory }
  tasks:
    - name: Test
      command: 'echo "hello world"'